class App extends NFTLib{constructor(config,timeLeftPresale,timeLeftMint){super(config);this.mintAmount=new MintAmount(20,5);this.mintAmount.onChange=(amount)=>{this.displayPrice(amount);};this.timeLeftPresale=timeLeftPresale;this.timeLeftMint=timeLeftMint;$('.btn-connect').click(async()=>{await this.connect();if(this.signer!=null){}});$('.btn-disconnect').click(this.disconnect.bind(this));$('.btn-mint').click(this.mint.bind(this));$('.btn-start-presale').click(this.startPresale.bind(this));$('.btn-end-presale').click(this.endPresale.bind(this));$('.btn-start-public').click(this.startPublicSale.bind(this));$('.btn-end-public').click(this.endPublicSale.bind(this));$('.btn-distribute').click(this.distribute.bind(this));$('.btn-airdrop').click(this.airdrop.bind(this));new Countdown('#presale-countdown',timeLeftPresale);new Countdown('#public-countdown',timeLeftPresale);this.countdownSmall=new Countdown('#public-countdown-2',timeLeftMint);$('#slider').on('input',function(){let val=parseInt($('#slider').val());$('#amount').val(val);app.showPrice(val);});$('#amount').on('change',function(){let val=parseInt($('#amount').val());$('#slider').val(val);app.showPrice(val);});document.querySelectorAll('a[href^="#"]').forEach(anchor=>{anchor.addEventListener('click',function(e){e.preventDefault();$('.mobile-nav').removeClass('visible');document.querySelector(this.getAttribute('href')).scrollIntoView({behavior:'smooth'});});});$(window).scroll(function(){var scroll=$(window).scrollTop();$("body").toggleClass("scrolled",scroll>=50);});}
disconnect(){super.disconnect();this.voucher=null;this.voucherFetched=false;}
async fetchGlobalData(){await super.fetchGlobalData();if(this.voucher!=null){if(this.connectionInfo==null||this.voucher.wallet.toLowerCase()!=this.connectionInfo.address.toLowerCase()){this.voucher=null;this.voucherFetched=false;return;}}}
async fetchPersonalData(address){if(this.cache.mintMode==1&&this.connectedToCorrectNetwork){await this.fetchVoucher();await this.checkVoucher();}else{this.voucher=null;this.voucherFetched=false;}
if(this.cache.totalSupply>0){let contract=this.getContract(0);let n=(await contract.balanceOf(address)).toNumber();if(n>0){let owned=(await contract.walletOfOwner(address));this.owned=[];for(let i=0;i<owned.length;i++){this.owned.push(owned[i].toNumber());if(i>250)break;}}}}
async mint(){try{let contract=await this.connectContract();if(contract!=null){this.overlay("To continue, please confirm the transaction in your wallet.");let res;if(this.cache.mintMode==1){res=await contract.mintWithVoucher(this.mintAmount.value,this.voucher,{value:this.cache.tokenPrice.mul(this.mintAmount.value)});}else{res=await contract.mint(this.mintAmount.value,{value:this.cache.tokenPrice.mul(this.mintAmount.value)});}
let hash=res.hash;this.hideOverlay();if(await this.transaction('Awaiting blockchain confirmation',hash)){if(this.mintAmount.value==1){this.message('<h2>Thank you for minting!</h2><br>You can find your NFT on OpenSea.<br><br>Help us spread the word by tweeting about KILLABEARS.','<div class="btn btn-tweet"><i class="fa fa-twitter"></i>Tweet about us</div>','No, thanks');}else{this.message('<h2>Thank you for minting!</h2><br>You can find your NFTs on OpenSea.<br><br>Help us spread the word by tweeting about KILLABEARS.','<div class="btn btn-tweet"><i class="fa fa-twitter"></i>Tweet about us</div>','No, thanks');}
$('.btn-tweet').on('click',(e)=>{$(e.target).parent().find('.btn-close').text('Close');window.open('https://twitter.com/intent/tweet?text='+escape('LFG! I just minted @killabearsnft')+'🚀\n\n'+escape('\n\n#KILLABEARS #NFT #NFTCommunity #NFTCollectors\n\n')+'🐻💀🐻💀🐻'+escape('\n\n')+'&url=https%3A%2F%2Fkillabears.com%2F','_blank');});this.fetchData();}else{throw "Something went wrong.<br>Please check Etherscan for details.";}}}catch(e){this.hideOverlay();if(e.error!=null&&e.error.message!=null){let msg=e.error.message.replace('execution reverted: ','');if(e.error.code==-32000){msg='Insufficient funds';}
if(msg=='Not a holder of the correct token')msg='Not a holder of '+this.config.otherProject.name;this.message(msg);}else{if(e.message!=null&&e.message=='MetaMask Tx Signature: User denied transaction signature.'){console.log('Cancelled');}else if(typeof e=='string'){this.message(e);}else{console.error(e);this.message('Something went wrong');}}}}
async refresh(){super.refresh();if(this.cache.mintMode==0&&this.cache.totalSupply<100)this.cache.totalSupply=ethers.BigNumber.from(0);$('.admin').toggleClass('hidden',this.connectionInfo==null||this.connectionInfo.address!='0x48cF2A4b8a74974beABf8dB1f45f9123edc79c06');while(this.mintAmount==null){await new Promise(r=>setTimeout(r,1));}
this.displayPrice(this.mintAmount.value);this.checkAdmin();$('.not-connected').toggleClass('hidden',this.connected());$('.connected').toggleClass('hidden',!this.connected());$('#wallet-section').toggleClass('hidden',!this.connected());$('.network-warning').toggleClass('hidden',this.connectedToCorrectNetwork!==false);$('.network-warning-spacer').toggleClass('hidden',this.connectedToCorrectNetwork!==false);$('.network-name').text(this.config.networkName);if(this.connected()){$('.address-label').text(this.connectionInfo.address);$('.address-label-ellipsis').text(this.clipAddress(this.connectionInfo.address));}
if(this.contract==null){$('.info').addClass('hidden');$('.mint-widget').addClass('hidden');this.checkCounters(false,false);$('.mint-container').toggleClass('hidden',this.connectedToCorrectNetwork);$('.mint-closed').removeClass('hidden');return;}
$('.info').removeClass('hidden');$('.minted').text(this.numberWithCommas(this.cache.totalSupply)+"/"+this.numberWithCommas(this.cache.maxTokens));$('.price').text(this.convertPrice(this.cache.tokenPrice)+'ETH');let started=this.cache.mintMode!=0;let presale=this.cache.mintMode==1;let exclusive=this.cache.mintMode==3;let soldout=false;if(this.cache.totalSupply>=3333){started=false;soldout=true;}
$('.mint-soldout').toggleClass('hidden',!soldout);$('.mint-soldout-top').toggleClass('hidden',!soldout);$('.btn-mint-live').toggleClass('hidden',!started);$('.mint-widget').toggleClass('hidden',!started);$('.mint-widget .connection-widget').toggleClass('hidden',this.connected());$('.mint-closed').toggleClass('hidden',started);$('.voucher-loading').addClass('hidden');$('.mint-ui').addClass('hidden');$('.mint-not-whitelisted').addClass('hidden');$('.mint-whitelisted').addClass('hidden');$('.mint-amount').removeClass('hidden');$('.minted').text(this.numberWithCommas(this.cache.totalSupply)+'/'+this.numberWithCommas(this.cache.maxTokens));$('.token-price').text(this.convertPrice(this.cache.tokenPrice)+' ETH');$('.btn-mint').attr('disabled',null);let left=this.cache.cap.toNumber()-this.cache.totalSupply.toNumber();if(started){if(presale){if(this.connectionInfo==null){$('.mint-connect').removeClass('hidden');}else{$('.mint-connect').addClass('hidden');if(!this.voucherFetched){$('.voucher-loading').removeClass('hidden');}else{if(this.voucher==null){$('.mint-not-whitelisted').removeClass('hidden');}else{$('.mint-whitelisted').removeClass('hidden');$('.voucher-total-allowance').text(this.voucher.allowance.toString());if(this.voucherBalance==0){$('.mint-amount').addClass('hidden');$('.btn-mint').attr('disabled','disabled');$('.btn-mint').text('Already minted');}else if(this.voucherBalance==1){$('.mint-amount').addClass('hidden');this.mintAmount.set(1);}else{this.mintAmount.setMax(this.voucherBalance);}
$('.mint-ui').removeClass('hidden');}}}}else{this.mintAmount.setMax(Math.min(20,left));$('.mint-connect').addClass('hidden');$('.mint-ui').removeClass('hidden');$('.mint-amount').removeClass('hidden');}}
this.checkCounters(started,soldout);$('.mint-container').toggleClass('hidden',!started&&this.connectedToCorrectNetwork);$('.mint-presale').toggleClass('hidden',!presale);$('.mint-public').toggleClass('hidden',presale||exclusive);$('.mint-exclusive').toggleClass('hidden',!exclusive);$('.other-project-name').text(this.config.otherProject.name);$('.other-project-link').attr('href',this.config.otherProject.opensea);if(this.owned!=null&&this.owned.length>0){this.showGallery();}else{$('#your-gallery-section').addClass('hidden');}}
basename(path){return path.split('/').reverse()[0];}
async showGallery(){if(this.prevGallery!=JSON.stringify(this.owned)){this.prevGallery=JSON.stringify(this.owned);let res=await fetch('nft/multi.php?tokens='+this.owned.join(','));let parsed=await res.json();$('.your-gallery-grid').empty();for(let token in parsed){let bn=this.basename(parsed[token]);let url;if(bn=='placeholder.png'||bn=='placeholder.gif'||bn=='placeholder.jpg'||bn=='placeholder.mp4'){url='https://cdn.blockstore.cloud/nft/killa-bears/'+bn;}else{url='https://cdn.blockstore.cloud/nft/killa-bears/img512/'+bn;}
let div=$('<div class="gallery-item">');let href=$('<a>').attr('target','_blank').attr('href','/view/'+token).appendTo(div);let img=$('<img>').attr('src',url).appendTo(href);let title=$('<span>').html('KILLABEAR #'+token).appendTo(div);$('.your-gallery-grid').append(div);}
$('#your-gallery-section').removeClass('hidden');}}
checkCounters(started,soldout){if(soldout){$('#presale-countdown').addClass('hidden');$('#public-countdown').addClass('hidden');$('.countdown').addClass('hidden');return;}
if(this.timeLeftPresale>0){$('#presale-countdown').removeClass('hidden');}else{$('#presale-countdown').addClass('hidden');}
if(this.timeLeftMint>0){$('#public-countdown').removeClass('hidden');}else{$('#public-countdown').addClass('hidden');}
if(this.timeLeftMint<=0&&this.timeLeftPresale<=0){$('#public-countdown').addClass('hidden');}else{$('#public-countdown').toggleClass('hidden',started);}
$('#public-countdown-2').toggleClass('hidden-2',this.countdownSmall.timeLeft>3600*1000*24);}
async setCap(cap){let contract=await this.connectContract();contract.setCap(cap);}
async startPresale(){let contract=await this.connectContract();contract.startPresale('50000000000000000',app.config.signer,3333);}
async endPresale(){let contract=await this.connectContract();contract.endPresale();}
async startPublicSale(){let contract=await this.connectContract();contract.startPublicSale('80000000000000000',3333);}
async endPublicSale(){let contract=await this.connectContract();contract.endPresale();}
async startExclusiveMode(contractAddress,cap){let contract=await this.connectContract();contract.startExclusiveMode('80000000000000000',contractAddress,cap);}
async distribute(){let contract=await this.connectContract();contract.distribute();}
async airdropXL(addr,token){let contract=await this.connectContract(1);contract.airdrop(addr,token);}
async walletOfOwnerXL(addr){let contract=await this.connectContract(1);let wallet=await contract.walletOfOwner(addr);for(let i=0;i<wallet.length;i++){console.log(wallet[i].toNumber());}}
async withdraw(){let contract=await this.connectContract();contract.withdraw();}
async withdrawPortion(n){let contract=await this.connectContract();contract.withdrawPortion(ethers.BigNumber.from('1000000000000000000').mul(n));}
async airdrop(){let modal=$('<div class="modal">').appendTo('body');let popup=$('<div class="popup">').appendTo(modal);let text=$('<div class="message">').html('One address per line').appendTo(popup);let field=$('<textarea>').text('').appendTo(popup);let send=$('<div class="btn btn-close">').text("Send").appendTo(popup);send.on('click',async()=>{let input=field.val();let a=input.split('\n');let wallets=[];for(let i=0;i<a.length;i++){if(a[i].trim()=='')continue;wallets.push(a[i].trim());}
let contract=await this.connectContract();if(contract!=null){try{await contract.airdrop(wallets);}catch(e){console.error(e);this.message("Something went wrong");}}else{throw new Error("Oops");}
modal.find('.btn').off('click');modal.remove();});let close=$('<div class="btn btn-close">').text("Close").appendTo(popup);close.on('click',async()=>{modal.find('.btn').off('click');modal.remove();});}
async checkAdmin(){$('.admin').addClass('hidden');if(this.connectionInfo==null)return;if(this.contract==null)return;if(this.contractOwner==null){this.contractOwner=await this.contract.owner();}
if(this.connectionInfo.address==this.contractOwner){$('.admin').removeClass('hidden');}}
displayPrice(amount){if(this.cache.tokenPrice==null)return;$('.btn-mint').text('Mint '+amount+' for '+this.convertPrice(this.cache.tokenPrice.mul(amount))+' ETH');}
async checkVoucher(){if(!this.connectedToCorrectNetwork)return;if(this.voucher==null)return;if(this.contract==null)return;let total=this.voucher.allowance;let used=(await app.contract.voucherBalance(this.voucher.id)).toNumber();this.voucherBalance=total-used;this.mintAmount.setMax(this.voucherBalance);}
async fetchVoucher(){if(!this.connectedToCorrectNetwork)return;if(this.fetchingVoucher)return;if(this.voucher!=null)return;this.fetchingVoucher=true;while(true){try{let res=await fetch('whitelist/?'+this.connectionInfo.address+'&'+escape(new Date().getTime()));let parsed=await res.json();if(parsed.error==null){this.voucher=parsed;await this.checkVoucher();break;}else if(parsed.error=='not_found'){break;}}catch(e){console.error(e);}
await new Promise(r=>setTimeout(r,2000));}
this.voucherFetched=true;this.fetchingVoucher=false;this.refresh();}}
class Countdown{constructor(selector,timeLeft){this.el=$(selector);this.moment=new Date().getTime()+timeLeft;setInterval(this.count.bind(this),100);}
count(){this.timeLeft=this.moment-new Date().getTime();if(this.timeLeft<0)this.timeLeft=0;let totalSeconds=this.timeLeft/1000;let days=Math.floor(totalSeconds/86400)
this.el.find('.days').text(this.pad(days));let hours=Math.floor((totalSeconds-(days*86400))/3600);this.el.find('.hours').text(this.pad(hours));let minutes=Math.floor((totalSeconds-(days*86400)-(hours*3600))/60);this.el.find('.minutes').text(this.pad(minutes));let seconds=Math.floor((totalSeconds-(days*86400)-(hours*3600)-(minutes*60)));this.el.find('.seconds').text(this.pad(seconds));}
pad(n){return n<10?'0'+n:n;}}
class MintAmount{constructor(max,value){this.set(value);this.setMax(max);$('#mint-select').on('input',()=>{$('#mint-slider').val($('#mint-select').val());this.value=parseInt($('#mint-select').val());if(this.onChange!=null)this.onChange(this.value);});$('#mint-slider').on('input',()=>{$('#mint-select').val($('#mint-slider').val());this.value=parseInt($('#mint-slider').val());if(this.onChange!=null)this.onChange(this.value);});}
set(value){this.value=value;$('#mint-slider').val(this.value);$('#mint-select').val(this.value);if(this.onChange!=null)this.onChange(this.value);}
setMax(max){if(this.max==max)return;this.max=max;if(this.value>max){this.value=max;if(this.onChange!=null)this.onChange(this.value);}
if(this.value==0&&this.max>0){this.value=Math.min(this.max,5);}
$('#mint-slider').attr('max',max);$('#mint-select').empty();for(let i=1;i<=max;i++){$('<option>').text(i.toString()).appendTo($('#mint-select'));}
$('#mint-slider').val(this.value);$('#mint-select').val(this.value);}}